from distutils.core import setup
from setuptools import find_packages

setup(name='plantextract',
      version='0.1.0',
      description='Python Plant Extract Document processor',
      author='Brett Francis',
#      package_dir = {'': ''},
      packages=find_packages('plantextract'),
      package_dir={'':'plantextract'},
#      include_package_data=True,
      package_data={'plantextract' : ['smdx-files/*.xml', 'xsd/*.xsd'],},
#      data_files=[('smdx-xml', ['smdx-files/smdx_00001.xml', 'smdx-files/smdx_00002.xml',
#                                'smdx-files/smdx_00010.xml', 'smdx-files/smdx_00011.xml',
#                                'smdx-files/smdx_00012.xml', 'smdx-files/smdx_00013.xml',
#                                'smdx-files/smdx_00014.xml', 'smdx-files/smdx_00015.xml',
#                                'smdx-files/smdx_00016.xml', 'smdx-files/smdx_00017.xml',
#                                'smdx-files/smdx_00018.xml', 'smdx-files/smdx_00019.xml',
#                                'smdx-files/smdx_00101.xml', 'smdx-files/smdx_00102.xml',
#                                'smdx-files/smdx_00103.xml', 'smdx-files/smdx_00111.xml',
#                                'smdx-files/smdx_00112.xml', 'smdx-files/smdx_00113.xml',
#                                'smdx-files/smdx_00120.xml', 'smdx-files/smdx_00121.xml',
#                                'smdx-files/smdx_00122.xml', 'smdx-files/smdx_00123.xml',
#                                'smdx-files/smdx_00124.xml', 'smdx-files/smdx_00125.xml',
#                                'smdx-files/smdx_00126.xml', 'smdx-files/smdx_00127.xml',
#                                'smdx-files/smdx_00128.xml', 'smdx-files/smdx_00129.xml',
#                                'smdx-files/smdx_00130.xml', 'smdx-files/smdx_00131.xml',
#                                'smdx-files/smdx_00132.xml', 'smdx-files/smdx_00133.xml',
#                                'smdx-files/smdx_00134.xml', 'smdx-files/smdx_00201.xml',
#                                'smdx-files/smdx_00202.xml', 'smdx-files/smdx_00203.xml',
#                                'smdx-files/smdx_00204.xml', 'smdx-files/smdx_00211.xml',
#                                'smdx-files/smdx_00212.xml', 'smdx-files/smdx_00213.xml']),
#                               # ...]),
#                  ('xsd', ['xsd/smdx.xsd', 'xsd/sunspec_data.xsd', 'xsd/sunspec_ws.xsd',
#                           'xsd/sunspec_plant_extract.xsd'])],
      install_requires=["lxml >= 3.0"],
      keywords = "sunspec plant extract",
      )